.TH CLOVER 1 "April 2025" "Clover 1.0" "User Commands"
.SH NAME
clover \- your awesome tool for backup and whatever else
.SH SYNOPSIS
.B clover
[\fIoptions\fR] [\fIarguments\fR]
.SH DESCRIPTION
Clover is a tool designed to help with backup management and other system tasks.

This program does awesome things.

.SH OPTIONS
.TP
.BR -h ", " --help
Show help information and exit.

.TP
.BR -v ", " --version
Display version information.

.SH EXAMPLES
Run clover normally:
.B
clover

Run clover with backup options:
.B
clover --backup /path/to/files

.SH AUTHOR
Hyrum Hendrickson <hyrum@example.com>

.SH SEE ALSO
bash(1), git(1)
