#!/bin/bash

# initalization
cd /usr/local/lib/clover
source scripts/commands.sh


# main loop
input="start"
while [[ "$input" != "quit" && "$input" != "exit" ]]; do
	run_command "$input"
	echo -n '> '
	read input
done

# exit process
cat assets/thanks.txt


