#!/bin/bash
# Clover - Data management tool for Linux
# initalization
cd /usr/local/lib/clover

# Source utility functions
source scripts/data_utils.sh
source scripts/commands.sh

# Check dependencies on startup
check_dependencies

# main loop
input="start"
while [[ "$input" != "quit" && "$input" != "exit" ]]; do
	run_command "$input"
	echo -n '> '
	read input
done

# exit process
cat assets/thanks.txt

